# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/mathis/Cours/S8/Projet Majeur/Projet-Majeure"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/mathis/Cours/S8/Projet Majeur/Projet-Majeure"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mathis/Cours/S8/Projet Majeur/Projet-Majeure/CMakeFiles" "/home/mathis/Cours/S8/Projet Majeur/Projet-Majeure//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mathis/Cours/S8/Projet Majeur/Projet-Majeure/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named coastal-erosion

# Build rule for target.
coastal-erosion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coastal-erosion
.PHONY : coastal-erosion

# fast build rule for target.
coastal-erosion/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/build
.PHONY : coastal-erosion/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/CMakeFiles/uninstall.dir/build.make libs/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/src/CMakeFiles/glfw.dir/build.make libs/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/src/CMakeFiles/update_mappings.dir/build.make libs/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

libs/glad/src/glad.o: libs/glad/src/glad.c.o
.PHONY : libs/glad/src/glad.o

# target to build an object file
libs/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/libs/glad/src/glad.c.o
.PHONY : libs/glad/src/glad.c.o

libs/glad/src/glad.i: libs/glad/src/glad.c.i
.PHONY : libs/glad/src/glad.i

# target to preprocess a source file
libs/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/libs/glad/src/glad.c.i
.PHONY : libs/glad/src/glad.c.i

libs/glad/src/glad.s: libs/glad/src/glad.c.s
.PHONY : libs/glad/src/glad.s

# target to generate assembly for a file
libs/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/libs/glad/src/glad.c.s
.PHONY : libs/glad/src/glad.c.s

libs/imgui/backends/imgui_impl_glfw.o: libs/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_glfw.o

# target to build an object file
libs/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.o

libs/imgui/backends/imgui_impl_glfw.i: libs/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
libs/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.i

libs/imgui/backends/imgui_impl_glfw.s: libs/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
libs/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.s

libs/imgui/backends/imgui_impl_opengl3.o: libs/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
libs/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : libs/imgui/backends/imgui_impl_opengl3.cpp.o

libs/imgui/backends/imgui_impl_opengl3.i: libs/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
libs/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_opengl3.cpp.i

libs/imgui/backends/imgui_impl_opengl3.s: libs/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
libs/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_opengl3.cpp.s

libs/imgui/imgui.o: libs/imgui/imgui.cpp.o
.PHONY : libs/imgui/imgui.o

# target to build an object file
libs/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui.cpp.o
.PHONY : libs/imgui/imgui.cpp.o

libs/imgui/imgui.i: libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.i

# target to preprocess a source file
libs/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.cpp.i

libs/imgui/imgui.s: libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.s

# target to generate assembly for a file
libs/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.cpp.s

libs/imgui/imgui_draw.o: libs/imgui/imgui_draw.cpp.o
.PHONY : libs/imgui/imgui_draw.o

# target to build an object file
libs/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_draw.cpp.o
.PHONY : libs/imgui/imgui_draw.cpp.o

libs/imgui/imgui_draw.i: libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.i

# target to preprocess a source file
libs/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.cpp.i

libs/imgui/imgui_draw.s: libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.s

# target to generate assembly for a file
libs/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.cpp.s

libs/imgui/imgui_tables.o: libs/imgui/imgui_tables.cpp.o
.PHONY : libs/imgui/imgui_tables.o

# target to build an object file
libs/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_tables.cpp.o
.PHONY : libs/imgui/imgui_tables.cpp.o

libs/imgui/imgui_tables.i: libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.i

# target to preprocess a source file
libs/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.cpp.i

libs/imgui/imgui_tables.s: libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.s

# target to generate assembly for a file
libs/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.cpp.s

libs/imgui/imgui_widgets.o: libs/imgui/imgui_widgets.cpp.o
.PHONY : libs/imgui/imgui_widgets.o

# target to build an object file
libs/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_widgets.cpp.o
.PHONY : libs/imgui/imgui_widgets.cpp.o

libs/imgui/imgui_widgets.i: libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.i

# target to preprocess a source file
libs/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.cpp.i

libs/imgui/imgui_widgets.s: libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.s

# target to generate assembly for a file
libs/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.cpp.s

src/erosion/erosion_system.o: src/erosion/erosion_system.cpp.o
.PHONY : src/erosion/erosion_system.o

# target to build an object file
src/erosion/erosion_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/erosion/erosion_system.cpp.o
.PHONY : src/erosion/erosion_system.cpp.o

src/erosion/erosion_system.i: src/erosion/erosion_system.cpp.i
.PHONY : src/erosion/erosion_system.i

# target to preprocess a source file
src/erosion/erosion_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/erosion/erosion_system.cpp.i
.PHONY : src/erosion/erosion_system.cpp.i

src/erosion/erosion_system.s: src/erosion/erosion_system.cpp.s
.PHONY : src/erosion/erosion_system.s

# target to generate assembly for a file
src/erosion/erosion_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/erosion/erosion_system.cpp.s
.PHONY : src/erosion/erosion_system.cpp.s

src/erosion/hydraulic_erosion.o: src/erosion/hydraulic_erosion.cpp.o
.PHONY : src/erosion/hydraulic_erosion.o

# target to build an object file
src/erosion/hydraulic_erosion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/erosion/hydraulic_erosion.cpp.o
.PHONY : src/erosion/hydraulic_erosion.cpp.o

src/erosion/hydraulic_erosion.i: src/erosion/hydraulic_erosion.cpp.i
.PHONY : src/erosion/hydraulic_erosion.i

# target to preprocess a source file
src/erosion/hydraulic_erosion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/erosion/hydraulic_erosion.cpp.i
.PHONY : src/erosion/hydraulic_erosion.cpp.i

src/erosion/hydraulic_erosion.s: src/erosion/hydraulic_erosion.cpp.s
.PHONY : src/erosion/hydraulic_erosion.s

# target to generate assembly for a file
src/erosion/hydraulic_erosion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/erosion/hydraulic_erosion.cpp.s
.PHONY : src/erosion/hydraulic_erosion.cpp.s

src/external/perlin/simplexnoise1234.o: src/external/perlin/simplexnoise1234.cpp.o
.PHONY : src/external/perlin/simplexnoise1234.o

# target to build an object file
src/external/perlin/simplexnoise1234.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/external/perlin/simplexnoise1234.cpp.o
.PHONY : src/external/perlin/simplexnoise1234.cpp.o

src/external/perlin/simplexnoise1234.i: src/external/perlin/simplexnoise1234.cpp.i
.PHONY : src/external/perlin/simplexnoise1234.i

# target to preprocess a source file
src/external/perlin/simplexnoise1234.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/external/perlin/simplexnoise1234.cpp.i
.PHONY : src/external/perlin/simplexnoise1234.cpp.i

src/external/perlin/simplexnoise1234.s: src/external/perlin/simplexnoise1234.cpp.s
.PHONY : src/external/perlin/simplexnoise1234.s

# target to generate assembly for a file
src/external/perlin/simplexnoise1234.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/external/perlin/simplexnoise1234.cpp.s
.PHONY : src/external/perlin/simplexnoise1234.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ocean/ocean.o: src/ocean/ocean.cpp.o
.PHONY : src/ocean/ocean.o

# target to build an object file
src/ocean/ocean.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/ocean/ocean.cpp.o
.PHONY : src/ocean/ocean.cpp.o

src/ocean/ocean.i: src/ocean/ocean.cpp.i
.PHONY : src/ocean/ocean.i

# target to preprocess a source file
src/ocean/ocean.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/ocean/ocean.cpp.i
.PHONY : src/ocean/ocean.cpp.i

src/ocean/ocean.s: src/ocean/ocean.cpp.s
.PHONY : src/ocean/ocean.s

# target to generate assembly for a file
src/ocean/ocean.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/ocean/ocean.cpp.s
.PHONY : src/ocean/ocean.cpp.s

src/ocean/wave.o: src/ocean/wave.cpp.o
.PHONY : src/ocean/wave.o

# target to build an object file
src/ocean/wave.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/ocean/wave.cpp.o
.PHONY : src/ocean/wave.cpp.o

src/ocean/wave.i: src/ocean/wave.cpp.i
.PHONY : src/ocean/wave.i

# target to preprocess a source file
src/ocean/wave.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/ocean/wave.cpp.i
.PHONY : src/ocean/wave.cpp.i

src/ocean/wave.s: src/ocean/wave.cpp.s
.PHONY : src/ocean/wave.s

# target to generate assembly for a file
src/ocean/wave.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/ocean/wave.cpp.s
.PHONY : src/ocean/wave.cpp.s

src/renderer/camera.o: src/renderer/camera.cpp.o
.PHONY : src/renderer/camera.o

# target to build an object file
src/renderer/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/camera.cpp.o
.PHONY : src/renderer/camera.cpp.o

src/renderer/camera.i: src/renderer/camera.cpp.i
.PHONY : src/renderer/camera.i

# target to preprocess a source file
src/renderer/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/camera.cpp.i
.PHONY : src/renderer/camera.cpp.i

src/renderer/camera.s: src/renderer/camera.cpp.s
.PHONY : src/renderer/camera.s

# target to generate assembly for a file
src/renderer/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/camera.cpp.s
.PHONY : src/renderer/camera.cpp.s

src/renderer/mesh.o: src/renderer/mesh.cpp.o
.PHONY : src/renderer/mesh.o

# target to build an object file
src/renderer/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/mesh.cpp.o
.PHONY : src/renderer/mesh.cpp.o

src/renderer/mesh.i: src/renderer/mesh.cpp.i
.PHONY : src/renderer/mesh.i

# target to preprocess a source file
src/renderer/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/mesh.cpp.i
.PHONY : src/renderer/mesh.cpp.i

src/renderer/mesh.s: src/renderer/mesh.cpp.s
.PHONY : src/renderer/mesh.s

# target to generate assembly for a file
src/renderer/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/mesh.cpp.s
.PHONY : src/renderer/mesh.cpp.s

src/renderer/renderer.o: src/renderer/renderer.cpp.o
.PHONY : src/renderer/renderer.o

# target to build an object file
src/renderer/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/renderer.cpp.o
.PHONY : src/renderer/renderer.cpp.o

src/renderer/renderer.i: src/renderer/renderer.cpp.i
.PHONY : src/renderer/renderer.i

# target to preprocess a source file
src/renderer/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/renderer.cpp.i
.PHONY : src/renderer/renderer.cpp.i

src/renderer/renderer.s: src/renderer/renderer.cpp.s
.PHONY : src/renderer/renderer.s

# target to generate assembly for a file
src/renderer/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/renderer.cpp.s
.PHONY : src/renderer/renderer.cpp.s

src/renderer/shader.o: src/renderer/shader.cpp.o
.PHONY : src/renderer/shader.o

# target to build an object file
src/renderer/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/shader.cpp.o
.PHONY : src/renderer/shader.cpp.o

src/renderer/shader.i: src/renderer/shader.cpp.i
.PHONY : src/renderer/shader.i

# target to preprocess a source file
src/renderer/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/shader.cpp.i
.PHONY : src/renderer/shader.cpp.i

src/renderer/shader.s: src/renderer/shader.cpp.s
.PHONY : src/renderer/shader.s

# target to generate assembly for a file
src/renderer/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/renderer/shader.cpp.s
.PHONY : src/renderer/shader.cpp.s

src/terrain/bruit.o: src/terrain/bruit.cpp.o
.PHONY : src/terrain/bruit.o

# target to build an object file
src/terrain/bruit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/bruit.cpp.o
.PHONY : src/terrain/bruit.cpp.o

src/terrain/bruit.i: src/terrain/bruit.cpp.i
.PHONY : src/terrain/bruit.i

# target to preprocess a source file
src/terrain/bruit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/bruit.cpp.i
.PHONY : src/terrain/bruit.cpp.i

src/terrain/bruit.s: src/terrain/bruit.cpp.s
.PHONY : src/terrain/bruit.s

# target to generate assembly for a file
src/terrain/bruit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/bruit.cpp.s
.PHONY : src/terrain/bruit.cpp.s

src/terrain/map.o: src/terrain/map.cpp.o
.PHONY : src/terrain/map.o

# target to build an object file
src/terrain/map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/map.cpp.o
.PHONY : src/terrain/map.cpp.o

src/terrain/map.i: src/terrain/map.cpp.i
.PHONY : src/terrain/map.i

# target to preprocess a source file
src/terrain/map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/map.cpp.i
.PHONY : src/terrain/map.cpp.i

src/terrain/map.s: src/terrain/map.cpp.s
.PHONY : src/terrain/map.s

# target to generate assembly for a file
src/terrain/map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/map.cpp.s
.PHONY : src/terrain/map.cpp.s

src/terrain/scene.o: src/terrain/scene.cpp.o
.PHONY : src/terrain/scene.o

# target to build an object file
src/terrain/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/scene.cpp.o
.PHONY : src/terrain/scene.cpp.o

src/terrain/scene.i: src/terrain/scene.cpp.i
.PHONY : src/terrain/scene.i

# target to preprocess a source file
src/terrain/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/scene.cpp.i
.PHONY : src/terrain/scene.cpp.i

src/terrain/scene.s: src/terrain/scene.cpp.s
.PHONY : src/terrain/scene.s

# target to generate assembly for a file
src/terrain/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/scene.cpp.s
.PHONY : src/terrain/scene.cpp.s

src/terrain/terrain.o: src/terrain/terrain.cpp.o
.PHONY : src/terrain/terrain.o

# target to build an object file
src/terrain/terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/terrain.cpp.o
.PHONY : src/terrain/terrain.cpp.o

src/terrain/terrain.i: src/terrain/terrain.cpp.i
.PHONY : src/terrain/terrain.i

# target to preprocess a source file
src/terrain/terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/terrain.cpp.i
.PHONY : src/terrain/terrain.cpp.i

src/terrain/terrain.s: src/terrain/terrain.cpp.s
.PHONY : src/terrain/terrain.s

# target to generate assembly for a file
src/terrain/terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coastal-erosion.dir/build.make CMakeFiles/coastal-erosion.dir/src/terrain/terrain.cpp.s
.PHONY : src/terrain/terrain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... coastal-erosion"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... libs/glad/src/glad.o"
	@echo "... libs/glad/src/glad.i"
	@echo "... libs/glad/src/glad.s"
	@echo "... libs/imgui/backends/imgui_impl_glfw.o"
	@echo "... libs/imgui/backends/imgui_impl_glfw.i"
	@echo "... libs/imgui/backends/imgui_impl_glfw.s"
	@echo "... libs/imgui/backends/imgui_impl_opengl3.o"
	@echo "... libs/imgui/backends/imgui_impl_opengl3.i"
	@echo "... libs/imgui/backends/imgui_impl_opengl3.s"
	@echo "... libs/imgui/imgui.o"
	@echo "... libs/imgui/imgui.i"
	@echo "... libs/imgui/imgui.s"
	@echo "... libs/imgui/imgui_draw.o"
	@echo "... libs/imgui/imgui_draw.i"
	@echo "... libs/imgui/imgui_draw.s"
	@echo "... libs/imgui/imgui_tables.o"
	@echo "... libs/imgui/imgui_tables.i"
	@echo "... libs/imgui/imgui_tables.s"
	@echo "... libs/imgui/imgui_widgets.o"
	@echo "... libs/imgui/imgui_widgets.i"
	@echo "... libs/imgui/imgui_widgets.s"
	@echo "... src/erosion/erosion_system.o"
	@echo "... src/erosion/erosion_system.i"
	@echo "... src/erosion/erosion_system.s"
	@echo "... src/erosion/hydraulic_erosion.o"
	@echo "... src/erosion/hydraulic_erosion.i"
	@echo "... src/erosion/hydraulic_erosion.s"
	@echo "... src/external/perlin/simplexnoise1234.o"
	@echo "... src/external/perlin/simplexnoise1234.i"
	@echo "... src/external/perlin/simplexnoise1234.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ocean/ocean.o"
	@echo "... src/ocean/ocean.i"
	@echo "... src/ocean/ocean.s"
	@echo "... src/ocean/wave.o"
	@echo "... src/ocean/wave.i"
	@echo "... src/ocean/wave.s"
	@echo "... src/renderer/camera.o"
	@echo "... src/renderer/camera.i"
	@echo "... src/renderer/camera.s"
	@echo "... src/renderer/mesh.o"
	@echo "... src/renderer/mesh.i"
	@echo "... src/renderer/mesh.s"
	@echo "... src/renderer/renderer.o"
	@echo "... src/renderer/renderer.i"
	@echo "... src/renderer/renderer.s"
	@echo "... src/renderer/shader.o"
	@echo "... src/renderer/shader.i"
	@echo "... src/renderer/shader.s"
	@echo "... src/terrain/bruit.o"
	@echo "... src/terrain/bruit.i"
	@echo "... src/terrain/bruit.s"
	@echo "... src/terrain/map.o"
	@echo "... src/terrain/map.i"
	@echo "... src/terrain/map.s"
	@echo "... src/terrain/scene.o"
	@echo "... src/terrain/scene.i"
	@echo "... src/terrain/scene.s"
	@echo "... src/terrain/terrain.o"
	@echo "... src/terrain/terrain.i"
	@echo "... src/terrain/terrain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

